Another stab at tempfile
Tinche/aiofiles pull request #56
Opened 2018-10-25 19:23 UTC by alemigo

Async tempfile implementation following the existing structure, with a bit extra for SpooledTemporaryFile where delegation is not required unless the in-memory stream is rolled to disk.

2020-05-06 00:58 UTC, shaqarava commented
Can you please fix the conflict if you have time? We need a tempfile rolled in. It's been years.

2020-05-06 10:32 UTC, alemigo commented
@Tinche - do you have interest to add this?  Can update the pull request and add testing if helpful

2020-05-09 13:08 UTC, alemigo commented
> Can you please fix the conflict if you have time? We need a tempfile rolled in. It's been years since adding it was first talked about. Seems like this one should have been merged.

updated

2020-09-28 04:43 UTC, CMCDragonkai commented
Any update on whether this fixes #20?

2020-09-28 10:04 UTC, alemigo commented
you can try https://github.com/alemigo/asynctempfile in the meantime

2020-09-28 11:49 UTC, CMCDragonkai commented
I think this PR can be squashed to be ready for merge.

2020-12-23 12:01 UTC, wagnerflo commented
Can a maintainer please confirm, that this will be merged so I can start using @alemigo's branch now and then switch back to a aiofiles release later?

2021-02-17 01:42 UTC, MajesticMullet commented
Will this be merged soon?

2021-02-26 16:25 UTC, JavierMartinezAlc commented
It will be really helpful if this is released

2021-02-26 17:16 UTC, alemigo commented
https://github.com/alemigo/asynctempfile is the same code for tempfile support as this PR

2021-02-26 17:17 UTC, Tinche commented
Alright, since there's interest I can merge this in. But it needs tests first.

2021-02-26 17:20 UTC, alemigo commented
> Alright, since there's interest I can merge this in. But it needs tests first.

Ok I will add

2021-02-26 17:25 UTC, Tinche commented
> > Alright, since there's interest I can merge this in. But it needs tests first.
> 
> Ok I will add

Excellent, thanks. Also some documentation on how to use it would be cool.

2021-03-05 23:55 UTC, Tinche requested changes
Looks good, left a couple of comments. Also the PR won't merge cleanly for me, might have to rebase on master. Thanks!

2021-03-05 23:55 UTC, Tinche commented on aiofiles/tempfile/__init__.py
> +__version__ = '0.1.1'
Don't think we need this

2021-03-05 23:55 UTC, Tinche commented on aiofiles/tempfile/__init__.py
> +@coroutine
Can we switch to async/await for all new code? We support 3.5+ which has it.

2021-03-30 14:13 UTC, alemigo commented
> Looks good, left a couple of comments. Also the PR won't merge cleanly for me, might have to rebase on master. Thanks!

Thx - made the changes

2021-03-31 23:50 UTC, Tinche approved these changes

2021-03-31 23:50 UTC, Tinche commented
Looks good, thanks a lot!

2021-03-31 23:50 UTC, merged